### ISSUE TITLE
Use different color for build failure

### ISSUE THREAD

**Issue by Wohops** [johann-beleites-sonarsource/quirrus#12]
Not all job failures have the same criticality for us. In my mind, `build` failures are _less_ important than `analysis` failures. Why? 

Why?
* A project that can not build requires some work but does not tell anything about our product
* A project that can not be analyzed means that one of our analyzers is experiencing a failure. We NEED to know it to act and fix it, asap.

I would suggest project build failures use another color, `blue` instead of `red` for instance, and keep `red` color for all the state that requires a squad's deep attention.

**Comment by johann-beleites-sonarsource** [comment]
Done in #11
